GiftList/Models/Gift.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GiftList.Models
{
    public class Gift
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Link { get; set; }
        public double Price { get; set; }
        public string ImageUrl { get; set; }
        public string Description { get; set; }
        public int GListId { get; set; }
        public virtual GList GList { get; set; }
        public string BookedBy { get; set; }
    }
}

GiftList/Controllers/GiftController.cs
using GiftList.Filters;
using GiftList.Models;
using GiftList.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.IO;
using System.Linq;
using System.Net.NetworkInformation;
using System.Security.Claims;
using System.Threading.Tasks;

namespace GiftList.Controllers
{

    public class GiftController : Controller
    {
        private readonly IGiftRepository _giftRepository;
        private readonly IGListRepository _gListRepository;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IHostingEnvironment _env;

        public GiftController(IGiftRepository giftRepository, UserManager<IdentityUser> userManager, IGListRepository gListRepository, IHostingEnvironment env)
        {
            _gListRepository = gListRepository;
            _giftRepository = giftRepository;
            _userManager = userManager;
            _env = env;
        }


        public IActionResult GiftsToList(int id, int? low, int? high)
        {
            var gifts = _giftRepository.LoadGifts(id, low, high).OrderBy(g => g.Name);
            var giftVM = new GiftVM()
            {
                Gifts = gifts.ToList(),
                LowFilter = low,
                HighFilter = high
            };
            return View(giftVM);
        }

        [HttpGet("/Gift/Reservation/{id}", Name = "reservation")]
        public IActionResult Reservation(int id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            _giftRepository.Book(id, userId);
            return Json(new
            {
                success = true
            });
        }

        [HttpGet("/Gift/Cancel/{id}", Name = "cancel")]
        public IActionResult Cancel(int id)
        {
            _giftRepository.Cancel(id);
            return Json(new
            {
                success = false
            });
        }

        [ServiceFilter(typeof(MenuActionFilter))]
        [HttpGet("Gift/Owner/{id}", Name = "owner")]
        public IActionResult Owner(int id, int? low, int? high)
        {
            GiftsToList(id, low, high);
            return View("Index");
        }

        [ServiceFilter(typeof(MenuActionFilter))]
        public IActionResult CreateList()
        {
            return View();
        }

        [Authorize(Roles = "Administrator")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ServiceFilter(typeof(MenuActionFilter))]
        public IActionResult CreateList(GList gList)
        {
            if (ModelState.IsValid)
            {
                _gListRepository.AddList(gList);
                return RedirectToAction("Owner", new { id = gList.Id });
            }
            return View(gList);
        }

        [Authorize(Roles = "Administrator")]
        [ServiceFilter(typeof(MenuActionFilter))]
        public IActionResult Create(string FileName)
        {
            if (!string.IsNullOrEmpty(FileName))
                ViewBag.ImgPath = "/images/" + FileName;
            return View();
        }

        [Authorize(Roles = "Administrator")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ServiceFilter(typeof(MenuActionFilter))]
        public IActionResult Create(Gift gift)
        {
            if (ModelState.IsValid)
            {
                _giftRepository.AddGift(gift);
                return RedirectToAction("Owner", new { id = gift.GListId });
            }
            return View(gift);
        }

        [Authorize(Roles = "Administrator")]
        [ServiceFilter(typeof(MenuActionFilter))]
        public IActionResult Edit(int Id, string FileName)
        {
            var gift = _giftRepository.LoadGiftById(Id);

            if (gift == null)
                return NotFound();

            if (!string.IsNullOrEmpty(FileName))
                ViewBag.ImgPath = "/images/" + FileName;
            else
                ViewBag.ImgPath = gift.ImageUrl;

            return View(gift);
        }

        [Authorize(Roles = "Administrator")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ServiceFilter(typeof(MenuActionFilter))]
        public IActionResult Edit(Gift gift)
        {
            if (ModelState.IsValid)
            {
                _giftRepository.EditGift(gift);
                return RedirectToAction("Owner", new { id = gift.GListId });
            }
            return View(gift);
        }

        [Authorize(Roles = "Administrator")]
        [ServiceFilter(typeof(MenuActionFilter))]
        public IActionResult Delete(int Id)
        {
            var gift = _giftRepository.LoadGiftById(Id);

            if (gift == null)
                return NotFound();

            return View(gift);
        }

        [Authorize(Roles = "Administrator")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [ServiceFilter(typeof(MenuActionFilter))]
        public IActionResult DeleteConfirmed(int id, string imageUrl)
        {
            var gift = _giftRepository.LoadGiftById(id);
            _giftRepository.DeleteGift(gift);
            if (imageUrl != null)
            {
                var webRoot = _env.WebRootPath;
                var path = Path.Combine(webRoot.ToString() + imageUrl);
                System.IO.File.Delete(path);
            }

            return RedirectToAction("Owner", new { id = gift.GListId });
        }

        [HttpPost("UploadFile")]
        public async Task<IActionResult> UploadFile(IFormCollection form)
        {
            var webRoot = _env.WebRootPath;
            var filePath = Path.Combine(webRoot.ToString() + "\\images\\" + form.Files[0].FileName);

            if (form.Files[0].FileName.Length > 0)
            {
                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    await form.Files[0].CopyToAsync(stream);
                }
            }
            if (Convert.ToString(form["Id"]) == string.Empty || Convert.ToString(form["Id"]) == "0")
            {
                return RedirectToAction("Create", new { FileName = Convert.ToString(form.Files[0].FileName) });
            }
            return RedirectToAction("Edit", new { FileName = Convert.ToString(form.Files[0].FileName), id = Convert.ToString(form["Id"])});
        }
    }
}

GiftList/Views/Gift/Create.cshtml
@model Gift

<h2>Dodaj prezent</h2>
<hr />
<div class="row">
    <div class="col-md-12">
        <div class="col-md-4">
            <form method="post" enctype="multipart/form-data" asp-action="UploadFile">
                <div class="form-group">
                    <input type="hidden" asp-for="Id" />
                    <label class="control-label"> Zdjęcie prezentu</label><br/>
                    <img src ="@ViewBag.ImgPath" height="300" width="300"/><br/>
                    <input type="file" name="file" style="margin-top:10px"/>
                </div>
                <div class="form-group">
                    <input type="submit" value="Załaduj zdjęcie" class="btn btn-primary"/>
                </div>
            </form>
        </div>
        
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="col-md-4">
                <div class="form-group">
                    <label asp-for="Name" class="control-label">Nazwa</label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Link" class="control-label">Link</label>
                    <input asp-for="Link" class="form-control" />
                    <span asp-validation-for="Link" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Price" class="control-label">Cena</label>
                    <input asp-for="Price" class="form-control" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label">Opis</label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="GList" class="control-label">Dziecko</label>
                    <select asp-for="GListId" class="form-control" asp-items="@(new SelectList(ViewBag.Glists, "Id", "OwnersName").ToList())">
                        <option value="">Wybierz dziecko</option>
                    </select>
                    <span asp-validation-for="GList" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-4">

                <input type="hidden" asp-for="ImageUrl" value="@ViewBag.ImgPath" />

                <div class="form-group">
                    <input type="submit" value="Dodaj prezent" class="btn btn-success" style="margin-top:30px" />
                    <a asp-controller="Home" asp-action="Index" class="btn btn-danger pull-right" style="margin-top:30px">Powrót</a>
                </div>
            </div>
        </form>
    </div>
</div>

GiftList/Views/Gift/CreateList.cshtml
@model GList

<h2>Dodaj kolejne dziecko</h2>
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="CreateList">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="col-md-4">
                <div class="form-group">
                    <label asp-for="OwnersName" class="control-label">Imię dziecka</label>
                    <input asp-for="OwnersName" class="form-control" />
                    <span asp-validation-for="OwnersName" class="text-danger"></span>
                </div>
                
            </div>
            <div class="col-md-4">

                @*<input type="hidden" asp-for="Id" />*@

                <div class="form-group">
                    <input type="submit" value="Dodaj dziecko" class="btn btn-success" style="margin-top:30px" />
                    <a asp-controller="Home" asp-action="Index" class="btn btn-danger pull-right" style="margin-top:30px">Powrót</a>
                </div>
            </div>
        </form>
    </div>
</div>

GiftList/Views/Gift/Delete.cshtml
@model Gift
<div>
    <div class="thumbnail">
        <div class="row">
            <div class="col-md-6">
                <img alt="@Model.Name" src="@Model.ImageUrl" height="500" width="500" />
            </div>
            <div class="col-md-6">
                <h2>Na pewno chcesz usunąć?</h2>
                <div class="pull-right">
                    <form asp-action="Delete">
                        <input type="hidden" asp-for="Id" />
                        <input type="submit" value="Usuń" class="btn btn-success" />
                        <input type="hidden" asp-for="ImageUrl"/>
                        <a asp-controller="Gift" asp-action="Owner" asp-route-id ="@Model.GListId" class="btn btn-success">Powrót</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

GiftList/Views/Gift/Edit.cshtml
@model Gift

<h2>Edytuj Prezent</h2>
<hr />
<div class="row">
    <div class="col-md-12">
        <div class="col-md-4">
            <form method="post" enctype="multipart/form-data" asp-action="UploadFile">
                <div class="form-group">
                    <input type="hidden" asp-for="Id" />
                    <label class="control-label"> Zdjęcie prezentu</label><br />
                    <img src="@ViewBag.ImgPath" height="300" width="300" /><br />
                    <input type="file" name="file" style="margin-top:10px" />
                </div>
                <div class="form-group">
                    <input type="submit" value="Załaduj zdjęcie" class="btn btn-primary" />
                </div>
            </form>
        </div>
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="BookedBy"/>
            <div class="col-md-4">
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Link" class="control-label"></label>
                    <input asp-for="Link" class="form-control" />
                    <span asp-validation-for="Link" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Price" class="control-label">Cena</label>
                    <input asp-for="Price" class="form-control" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="GListId" class="control-label"></label>
                    <select asp-for="GListId" class="form-control" asp-items="@(new SelectList(ViewBag.Glists, "Id", "OwnersName").ToList())">
                        <option value="">Wybierz dziecko</option>
                    </select>
                    <span asp-validation-for="GList" class="text-danger"></span>
                </div>
            </div>
            <div>
                <input type="hidden" asp-for="ImageUrl" value="@ViewBag.ImgPath" />
                <div class="form-group">
                    <input type="submit" value="Edytuj prezent" class="btn btn-success" style="margin-top:30px" />
                    <a asp-controller="Gift" asp-action="Owner" asp-route-id="@Model.GListId" class="btn btn-danger pull-right" style="margin-top:30px">Powrót</a>
                </div>
            </div>
        </form>
    </div>
</div>

GiftList/Views/Gift/Index.cshtml
@model GiftVM
@using System.Security.Claims;
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager
<div class="row">
    <div class="col-lg-3">

        <h2 class="my-4">Przedział cenowy</h2>
        <div class="list-group">
            <a asp-route="default" asp-route-low="0" asp-route-high="50" class="list-group-item">0-50</a>
            <a asp-route="default" asp-route-low="50" asp-route-high="100" class="list-group-item">51-100</a>
            <a asp-route="default" asp-route-low="100" asp-route-high="150" class="list-group-item">101-150</a>
            <a asp-route="default" asp-route-low="150" class="list-group-item">151+</a>
            <a asp-route="default" asp-route-low="null" asp-route-high="null" class="list-group-item">Wszystko</a>

        </div>
    </div>
    <div class="col-lg-9">
        <a asp-action="Create" class="btn btn-danger btn-sm">Dodaj nowy</a>
        <div class="row">
            @foreach (var gift in Model.Gifts)
            {
                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="card h-100">
                        <div class="frame">
                            <span class="helper"></span>
                            <img class="card-img-top" src=@gift.ImageUrl alt="">

                        </div>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="@gift.Link">@gift.Name</a>
                            </h4>
                            <h5>@gift.Price zł</h5>
                            <p class="card-text">@gift.Description</p>
                        </div>
                        @if (gift.BookedBy != null)
                        {
                            @if (@gift.BookedBy != @User.FindFirstValue(ClaimTypes.NameIdentifier))
                            {
                                <div class="card-footer form-group reservedforeign">
                                    <div>Zarezerwowany</div>
                                </div>
                            }
                            else
                            {
                                <div class="card-footer form-group reserved">
                                    <div data-gift-id="@gift.Id">Zarezerwowany</div>
                                </div>
                            }
                        }
                        else
                        {
                            @if (@User.FindFirstValue(ClaimTypes.NameIdentifier) != null)
                            {
                                <div class="card-footer form-group available">
                                    <div data-gift-id="@gift.Id">Zarezerwuj</div>
                                </div>
                            }
                            else
                            {
                                <div class="card-footer form-group unavailable">
                                    <div>Zaloguj się!</div>
                                </div>
                            }

                        }

                        @if (User.IsInRole("Administrator"))
                        {
                            <a asp-action="Edit" asp-route-id="@gift.Id" class="btn btn-success btn-sm" style="margin-bottom:3px">Edytuj</a>
                            <a asp-action="Delete" asp-route-id="@gift.Id" class="btn btn-success btn-sm" style="margin-bottom:3px">Usuń</a>
                        }


                    </div>
                </div>

            }
        </div>
    </div>
</div>
<script>
    var cancelfunction = function (event) {
        var buttonDiv = $(event.target);
        var giftid = buttonDiv.data('gift-id');
        $.ajax({
            type: "GET",
            url: "/Gift/Cancel/" + giftid,
            success: function (data) {
                buttonDiv.parent().removeClass("reserved").addClass("available");
                buttonDiv.text("Zarezerwuj");
                buttonDiv.off('click');
                buttonDiv.click(reservationfunction);
                toastr.success('You just cancelled your choice :(', null, { positionClass: "toast-bottom-right" })

            },
            error: function () {
                toastr.error('Something went wrong motherfucker', null, { positionClass: "toast-bottom-right" })
            }

        });
    }

    var reservationfunction = function (event) {
        var buttonDiv = $(event.target);
        var giftid = buttonDiv.data('gift-id');
        $.ajax({
            type: "GET",
            url: "/Gift/Reservation/" + giftid,
            success: function (data) {
                buttonDiv.parent().removeClass("available").addClass("reserved");
                buttonDiv.text("Zarezerwowany");
                buttonDiv.off('click');
                buttonDiv.click(cancelfunction);
                toastr.success('Good job you lazy son of a bitch!', null, { positionClass: "toast-bottom-right" })


            },
            error: function () {
                toastr.error('Something went wrong motherfucker', null, { positionClass: "toast-bottom-right" })
            }
        });
    }

    $(document).ready(function () {
        $('.card-footer.available div').click(reservationfunction);
        $('.card-footer.reserved div').click(cancelfunction);


    });
</script>





